version: '3.4'

services:
  takserver:
    image: "pvarki/takserver:4.7-RELEASE-32${DOCKER_TAG_EXTRA}"
    build:
      context: .
      dockerfile: Dockerfile
      cache_from: [ "pvarki/tak-server-dist:4.7-RELEASE-32" ]
    env_file:
      - 'takserver.env'
    depends_on:
      - "takdb"
    volumes:
      - 'takserver_logs:/opt/tak/data/logs'
      - 'takserver_certs:/opt/tak/data/certs'
    networks:
      - taknet
    ports:
      - '8443:8443'
      - '8444:8444'
      - '8446:8446'
      - '8089:8089'

  traefik:
    image: traefik:v2.2
    networks:
      - taknet
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "$PWD/traefik.local.toml:/etc/traefik/traefik.toml"

  takdb:
    image: postgis/postgis:15-3.3
    networks:
      - taknet
    env_file:
      - 'takserver.env'
    volumes:
      - 'takdb_data:/var/lib/postgresql/data'

networks:
  taknet:

volumes:
  takdb_data:
    driver: local
  takserver_logs:
    driver: local
  takserver_certs:
    driver: local
