on:
    pull_request:
    workflow_dispatch:

env:
  TAK_RELEASE: 5.7-RELEASE-32

jobs:
  checks:
    runs-on: arc-runner-set
    permissions:
      contents: read
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Prepare env file for hooks
        run: cp takserver.env.example takserver.env
      - name: Run prek
        uses: j178/prek-action@v2
        env:
          SKIP: no-commit-to-branch
      - name: Validate bumpversion
        uses: pvarki/config-ci-library/.github/actions/validate-bumpversion@main
      - name: validate coreconfig
        run: |
          docker compose build --progress plain takserver_initialization
          docker compose up takserver_config -d --wait || docker compose logs
          test $(docker inspect --format "{{json .State.Health.Status }}" takserver-takserver_config-1) = '"healthy"'
          docker compose down -v


  build_and_publish:
    runs-on: ubuntu-latest
    needs: [checks]
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Publish image
        uses: pvarki/config-ci-library/.github/actions/publish-image@main
        with:
          product: tak
          component: server
          target: run
          platforms: linux/amd64
          build-args: |
            TAK_RELEASE=${{ env.TAK_RELEASE }}
          dockerhub-username: ${{ vars.DOCKERHUB_USERNAME }}
          dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          acr-repo: ${{ vars.ACR_REPO }}
          acr-username: ${{ vars.ACR_USERNAME }}
          acr-token: ${{ secrets.ACR_TOKEN }}
